services:
  backend:
    image: myapp:${TARGET:-development}
    build:
      context: ..
      dockerfile: docker/backend.dockerfile
      target: ${TARGET:-development}
    labels:
      - "environment=${ENVIRONMENT:-unknown}"
    ports:
      - "8080:8080"
      - "7331:7331"
    restart: unless-stopped
    env_file:
      - ../config/.env.${ENVIRONMENT:-development}
    volumes:
      - ../src/backend:/app/
    

  db:
    image: postgres
    env_file:
      - ../config/.env.${ENVIRONMENT:-development}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: