services:
  backend:
    image: myapp:latest
    build:
      context: ..
      dockerfile: docker/backend.dockerfile
    labels:
      - "environment=${ENVIRONMENT:-unknown}"
    ports:
      - "8080:8080"
      - "7331:7331"
    restart: unless-stopped
    env_file:
      - ../config/.env.${ENVIRONMENT:-development}
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=mydatabase
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
    volumes:
      - ../src/backend:/app/
    

  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: